language: python
python:
- "3.5.2"
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov

services:
  - postgresql

before_script:
  - psql -c 'create database ireporterdb;' -U postgres

script:
  - pytest --cov

after_success:
  - coveralls
 
